services:
    _defaults:
            autowire: true
            autoconfigure: true

    Morgenbord\CoreBundle\:
        resource: '../src/'
        exclude:
            - '../vendor/morgenbord/core-bundle/src/Entity/'

    Morgenbord\CoreBundle\EventListener\UserWidgetListener:
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postLoad'
                entity: 'Morgenbord\CoreBundle\Entity\UserWidget'
                lazy: true
