services:
    _defaults:
            autowire: true
            autoconfigure: true

    # Makes sure the controllers and services benefits from autowiring
    MorgenBord\CoreBundle\:
        resource: '../src/'
        exclude:
            - '../vendor/morgenbord/core-bundle/src/DependencyInjection/'
            - '../vendor/morgenbord/core-bundle/src/Migrations/'
            - '../vendor/morgenbord/core-bundle/src/Entity/'