services:
    _defaults:
            autowire: true
            autoconfigure: true

    Morgenbord\CoreBundle\:
        resource: '../src/'
        exclude:
            - '../vendor/morgenbord/core-bundle/src/Entity/'
